### ISSUE TITLE
Verbiage Feedback

### ISSUE THREAD

**Issue by mustinov** [michaelguse/sandbox-preview#17]
I would suggest changing "What would you like information on?" to "What do you want to do with this sandbox for the XXX release?"

**Comment by michaelguse** [comment]
Let’s combine the status line above this text into a single question for the user. One option is: “What do you want to do with your PREVIEW sandbox CS87 for the upcoming Winter ‘19 release?”

**Comment by michaelguse** [comment]
Updated the staging environment accordingly.
