### ISSUE TITLE
nothing displayed if sandbox instance is typed in lowercase characters

### ISSUE THREAD

**Issue by mustinov** [michaelguse/sandbox-preview#2]
When I query a Sandbox instance with lowercase letters, no info is displayed

![image](https://user-images.githubusercontent.com/35305716/34784756-084ef40a-f5e4-11e7-8e69-e69cacd5f2f9.png)

**Comment by michaelguse** [comment]
Fixed issue in #4 by adding uppercase logic into query parameter
