### ISSUE TITLE
Ability to plan for sandbox refreshes 3 months in advance, instead of the typical 4-5 weeks

### ISSUE THREAD

**Issue by mustinov** [michaelguse/sandbox-preview#21]
This is a great tool. My customer has very complex Corporate environment to manage and they would like to calculate which Sandbox to refresh with 3 months in advance, as the regular 5-6 weeks timeframe (once Sandbox blog post is published) may be too short for them. Will this tool cover this case as well ? I know well that if an instance is a preview one this release, it may not be for the next release (although in most cases it will be), so I wonder if your tool will cover this calculation with more 2-3 months in advance.

**Comment by michaelguse** [comment]
I replied to Gianluca in Chatter on this. 

> Thank you for the positive response to the tool. My simple answer would be ‘Yes’ - the tool would allow you to lookup sandbox instances even 3 months in advance and provide you with a correct answer at a fairly high confidence. The caveat is, that it is possible that a sandbox might change it is status in the meantime, so the advice from the tool would a best effort answer, based on that days information. You probably would want to confirm your plans after the blog post comes out, to make sure no changes happened to any of your involved instances in the meantime. 
> We are going to make on-going changes to the tool during our Beta period and one area that will get adjusted for sure is the advice details that are provided at the different time period around a refresh timeline. We are looking at three phases effectively: (1) from Prod release to sandbox preview blog post; (2) from blog post to sandbox refresh date (refresh to preview window); and (3) from sandbox refresh date to Prod release rollout (Non-Preview window).
> One of our top priorities at the moment is to update the information on the page for the three different time periods.
> I hope this helps and please keep on providing such great feedback! Thanks!
