### ISSUE TITLE
Entering an invalid CS instance returns a blank page

### ISSUE THREAD

**Issue by mustinov** [michaelguse/sandbox-preview#7]
I entered 'CS0' as an instance (it's not a real sandbox), and was directed to a blank page. I think returning an error or "did you mean ____" suggestion might provide a better experience.

![image](https://user-images.githubusercontent.com/35305716/34850606-677670b4-f6db-11e7-8753-6d47c9777d7e.png)

repro: pretty simple bug to repro -- enter a fake CSx instance, or NAx or EUx or any other character string that isn't a real Sandbox name, and it returns a blank page - no error message or anything

**Comment by michaelguse** [comment]
Fixed as part of PR #24
