### ISSUE TITLE
Heroku site down

### ISSUE THREAD

**Issue by bacasystems-IT** [michaelguse/sandbox-preview#73]
**Describe the bug**
The heroku app doesnt load anymore.

**To Reproduce**
1. Go to http://sandbox-preview.herokuapp.com/

**Expected behavior**
Page loads

**Screenshots**
![image](https://github.com/michaelguse/sandbox-preview/assets/41757560/4af96bcf-4082-4588-850d-a838ddc85e4e)

**Desktop (please complete the following information):**
All browser imapct

**Additional context**
seems like heroku app got deleted.

**Comment by michaelguse** [comment]
My apologies for the recent downtime for the Sandbox Preview website! 

I had to change a few things and the site has a new home now, which unfortunately also means that it comes with a new URL:

https://sandbox-preview-prd-24f76e67b11e.herokuapp.com/

Please bookmark this new URL! 

I already registered a new, static domain for the site, to avoid this long URL name it currently has, and to make sure that the URL will not change in the future. I hope to have that change for the new, static domain name in place by next week. As soon as the new, static domain name is setup, I will send out another update with the new information.

Thank you for everyones patience and good luck in performing any necessary lookups - like sandbox queries, cheatsheet lookup or following a link to the TRUST maintenance page - to support yours or your customers sandbox instances for the upcoming Winter '24 preview period.
